discovery:
  image: sitedoph/discovery-service
  ports:
   - "8761:8761"
configserver:
  image: sitedoph/configuration-service
  ports:
   - "8888:8888"
  links:
   - discovery
airtrafficservice:
  image: sitedoph/air-traffic-service
  ports:
   - "9005:9005"
  links:
   - discovery
   - configserver
gateway:
  image: sitedoph/gateway-service
  ports:
   - "10000:10000"
  links:
   - discovery
   - configserver
   - airtrafficservice
